name: mashal_app
description: Release version of mashal

version: 3.0.920+53

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7
  get_it: ^7.6.0
  dio: ^5.2.1+1
  permission_handler: ^10.3.0
  shared_preferences: ^2.1.2
  geolocator: ^9.0.2
  flutter_svg: ^2.0.7
  sms_autofill: ^2.3.0
  persian_datetime_picker: ^2.6.0
  client_information: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appImages/new_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/appImages/
    - assets/images/bankImages/
    - assets/images/bills/
    - assets/images/drawerIcon/
    - assets/images/home_icons/
    - assets/images/icon/
    - assets/images/select_fuel_image/

  fonts:
    - family: IranSBold
      fonts:
        - asset: assets/fonts/iransans/IRANSansXFaNum-Bold.ttf
